### ISSUE TITLE
Dropbox

### ISSUE THREAD

**Issue by stackoverflow1453** [schmich/marinara#161]
Is it possible to sync pomodoro history by dropping the history file to dropbox or some other cloud or does this work only on local chrome? I am using a few machines and want to sync pomodoro history... Is it possible?

**Comment by schmich** [comment]
No, there's no way to automatically do it. You can export/import history between browsers, but it's still a manual process.

This was a mistake on my part. Issue #69 is the official issue for this problem, and is the next big task I will be focusing on. Once that issue is fixed, history will automatically sync across browsers via your Google account.

**Comment by stackoverflow1453** [comment]
If you can implement this into Marinara, it would be a big thing... It will be my go to tool and for others I think.

**Comment by schmich** [comment]
Agreed. I'm closing this issue in favor of #69.
