### ISSUE TITLE
no items "start focusing" "start break" in menu for Vivaldi browser

### ISSUE THREAD

**Issue by miroque** [schmich/marinara#205]
Shows only standart plugin menu 
1. Settings
2. Delete plugin
3. Hide icon

no any additional items for start or restart focusing, no items for start/stop breaks

**Comment by acicovic** [comment]
@miroque is this still an issue?

**Comment by miroque** [comment]
Yep, it's still an issue.

Vivaldi | 2.5.1525.48 (Stable channel) (64 бит)
-- | --
Версия | 29398d382527041597792325909ec48e07e1f5a6
ОС | Linux
JavaScript | V8 7.4.288.28
Flash | (Отключено)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.172 Safari/537.36 Vivaldi/2.5.1525.48
Командная строка | /usr/bin/vivaldi-stable --flag-switches-begin --flag-switches-end --save-page-as-mhtml

**Comment by acicovic** [comment]
Hi, Windows has this issue as well. It's a known Vivaldi limitation with bug number `VB-29932`. See here:

https://forum.vivaldi.net/topic/26419/extension-right-click-menu-lacks-it-s-own-menu-items
https://forum.vivaldi.net/topic/31313/different-experiences-with-wallabagger-extension

For everyone who's interested in getting this resolved, I suggest you to write in the above threads so we try to spark interest in solving this. @schmich I don't know if you would be interested in posting as an extension author, perhaps it could be more effective as your extension has lots of users. If there's any way I can help let me know.

Here's my post for the status of this issue (as of 11/6/19):
https://forum.vivaldi.net/post/299399

**Comment by schmich** [comment]
@acicovic Thanks for investigating, that helps a lot. It's tough to support non-Chrome browsers at the moment because while most have adopted Chrome's extension API, they all have their quirks like this that can be time consuming.

I can post there to add support for the feature, but it does sound like it's still a ways off.

There are a couple of workarounds that might work as features in both Vivaldi and Chrome:

1. [Hotkeys](https://developer.chrome.com/extensions/commands). Support user-defined hotkeys to control Pomodoros. This is [directly supported in Chrome](https://www.maketecheasier.com/assign-custom-hotkeys-chrome-extensions/), although it is a little hidden. Not sure if Vivaldi supports extension hotkeys.

2. [Add browser action UI](https://developer.chrome.com/extensions/browserAction). Add an option to change how primary/left-clicking on the Marinara toolbar icon behaves. Right now it just starts/pauses/resumes the timer, but it could instead pop up a small dialog that let's you control the flow similar to how the right-click context menu works today.

Thoughts?

**Comment by acicovic** [comment]
@schmich thank you so much for your answer and kind consideration.

It's certain that supporting third-party browsers is a hurdle and that main development time should be devoted to extension development instead of third-party browser quirks. Regarding your points:

**Hotkeys**: There are bugs regarding hotkeys and Vivaldi (for example https://forum.vivaldi.net/topic/31027/keyboard-shortcuts-not-working-with-extensions/19) but hotkeys could work (I've been occasionally using Vivaldi with Vimium and had no major problems). But it could be a waste to develop this just to find out it doesn't work. If you plan to do it anyway it could be an option and I think that some existing Chrome Marinara users would be happy to have hotkeys.

**Action UI**: This is a good way if it's not too much trouble for you. It should work in Vivaldi and others as almost all extensions show something on left click.

As a last resort, you could also add a new tab in Marinara's options with all the missing operations. This is slower (invoke options -> click tab -> click operation) but it gets the job done and it doesn't need to implement any changes in the way that the extension currently operates. No matter the browser used, this will definitely work. So it could be an alternative for browsers which are never going to be supported well. In that case, users will still be able to use Marinara. It's a workaround, but one I would be willing to live with if there's no other way.

**Comment by acicovic** [comment]
This is the menu currently shown by Vivaldi:

![image](https://user-images.githubusercontent.com/23142906/59296365-78b6c780-8c8e-11e9-95cd-ba87767f1a6e.png)

**Comment by kumamonishe** [comment]
I've got the same issue with Vivaldi 2.7.1628.33 -- I don't get the timer control menu not with left click, nor with right click :(

**Comment by miroque** [comment]
Vivaldi | 3.1.1929.45 (Stable channel) (64 бит)
-- | --
Версия | 1eb3263017ed42270818939fbff241845938a81f
ОС | Linux
JavaScript | V8 8.3.110.13
Flash | (Отключено)
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.119 Safari/537.36
Командная строка | /usr/bin/vivaldi-stable --flag-switches-begin --flag-switches-end --disable-webrtc-apm-in-audio-service --save-page-as-mhtml
Путь к исполняемому файлу | /opt/vivaldi/vivaldi

It's there! At last!
