### ISSUE TITLE
sounds doesn't work in brave browser

### ISSUE THREAD

**Issue by primordialcodes** [schmich/marinara#223]

**Comment by schmich** [comment]
Thanks for reporting this.

_I'm taking a few notes here for myself since I'm sure this issue will come up again for another browser._

I haven't done any testing on Brave at all, but it looks like Brave is treating the `Audio` API differently from Chrome. In particular, `Audio.play` doesn't just work in Brave (even in an extension):

![screen shot 2018-11-10 at 12 58 34 am](https://user-images.githubusercontent.com/1562839/48299588-d4646c80-e483-11e8-9bdd-0d8110aff43e.png)

The apparent workaround is to use `AudioContext` in the Web Audio API to play the sound instead. This works in both Brave and Chrome, however, there is a warning that it might stop working in the future once the Web Audio autoplay policy is re-enabled:

![screen shot 2018-11-10 at 1 02 26 am](https://user-images.githubusercontent.com/1562839/48299614-56ed2c00-e484-11e8-8e40-f8f2ace2bbda.png)

This seems like a dumb policy to enforce for _extensions_, but they might be exempt, we'll see.

I'll implement the fix above and publish a new version. If it happens to break again when they update the browser policy, feel free to resurrect this issue.

**Comment by schmich** [comment]
Version 18 published to the store. It should be available shortly.
