### ISSUE TITLE
Timer too small - make timer floating and resizable.  + standalone app for Mac would be great. TY

### ISSUE THREAD

**Issue by ShortyMcRib** [schmich/marinara#248]
Hi, thanks for a great tool.
It would be even better if the countdown timer was visible.  
As it is right now, it's too small on the Chrome toolbar.  

Can you make the countdown clock larger, resizable, and have it float on the screen?  
Maybe even an app that I can run on my Mac.

Thanks!

**Comment by schmich** [comment]
> It would be even better if the countdown timer was visible.
As it is right now, it's too small on the Chrome toolbar.

Unfortunately, I cannot control how the countdown timer is displayed in the toolbar in Chrome. I can set the color and text, but the browser determines the font size and spacing.

> Can you make the countdown clock larger, resizable, and have it float on the screen?

This sounds a bit like #176. The idea is to have a dedicated tab for displaying the time remaining. It is a feature I plan on adding in the near future. I added your feedback there.

> Maybe even an app that I can run on my Mac.

I have considered creating a standalone app, and I think it will happen at some point, but it is a much larger and more significant effort that will take some time.

I am closing this issue since I think it is already covered by existing issues that you can track. Thanks for the feedback!
